import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../components/Header.js";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className} relative>
        <Header />
        {children}
      </body>
    </html>
  );
}
